name: flavor_text
description: A lightweight and fully customisable text parser for Flutter.
version: 0.1.0
homepage: https://gitlab.com/wolfenrain/flavor_text
author: Jochum van der Ploeg

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  dartlin: ^0.6.0
  flutter:
    sdk: flutter
  xml: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
