name: flavor_text
description: A lightweight and fully customisable text parser for Flutter.
version: 1.0.0
homepage: https://gitlab.com/wolfenrain/flavor_text

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  dartlin: ^0.6.0
  flutter:
    sdk: flutter
  xml: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.1.1
